# SeptemberRain basic config

server-date: 0
days-in-year: 120
research-per-day: 1
current-era: dawn
eras:
  - dawn
  - iron-age
  - antiquity
  - middle-age
  - early-modern
  - late-modern
  - contemporary
era-multiplier:
  dawn: 1
  stone-age: 1
  bronze-age: 1.2
  iron-age: 1.3
  middle-age: 1.5
  early-modern: 1.75
  late-modern: 1.75
  contemporary: 2
era-years:
  dawn: 0
  iron-age: 90
  antiquity: 150
  middle-age: 210
  early-modern: 255
  late-modern: 285
  contemporary: 300
